### ISSUE TITLE
Choose Data Set and Research Questions

### ISSUE THREAD

**Issue by yhchen20** [UBC-MDS/DSCI_522_Group_18#1]
Each one provide three data sets with a research questions before 20th, Nov

**Comment by yhchen20** [comment]
1. Census Income Dataset https://archive.ics.uci.edu/ml/datasets/Census+Income
research question: Whether or not a person makes over 50K a year?
2. Wine Dataset https://archive.ics.uci.edu/ml/datasets/Wine
research question: Among the three different cultivars, which one is the wine derived from?
3. Dota2 Games Results Data Set  https://archive.ics.uci.edu/ml/datasets/Dota2+Games+Results
research question: What are the five strongest heroes and what are the five weakest ones? Does the game mode and game type influence the result?

**Comment by AishwaryaGopal12** [comment]
1.  Credit Card Default Dataset: https://archive.ics.uci.edu/ml/machine-learning-databases/00350/
    Question: Predict whether a customer will default on his credit card payment based on certain factors
2. Real Estate Valuation : https://archive.ics.uci.edu/ml/machine-learning-databases/00477/
    Question: Estimate the value of a property based on features such as number of convenience stores nearby, age of the 
    property etc. Is any particular feature outweighing the rest when predicting the value of the property? Has the price of a 
    property increased or decreased in a period of one year?

**Comment by fei-chang** [comment]
1. [Census Income Dataset](https://archive.ics.uci.edu/ml/datasets/Census+Income)
Research Question: From the data given, predict whether or not a person can earn more than 50k.
2. [Bank Marketing Data Set](https://archive.ics.uci.edu/ml/datasets/Bank+Marketing)
Research Question: From the data given, predict whether or not the client will subscribe a term deposit.
3. [Apartment for rent classified Data Set](https://archive.ics.uci.edu/ml/datasets/Apartment+for+rent+classified)
Research Question: From the data given, estimate the rental price of apartment.

**Comment by yhchen20** [comment]
We would use Census Income Dataset to predict whether or not a person can earn more than 50k.
