### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by abaghela** [UBC-MDS/DSCI_522_Group_18#9]
Some questionsn that come to mind when reading your proposal: 
- why chose 50K as the cut off?
- why chose logistic regression? Can you compare this to other models? Which ones? 
- what measure of ML accuracy will you use? AUC, F1, or just plain accuracy?

**Comment by abaghela** [comment]
Also, the correlation network did not add much. Could probably have stayed in the EDA files.

**Comment by AishwaryaGopal12** [comment]
Added reasoning for why choose 50K as the cut off in the introduction section of the report

**Comment by AishwaryaGopal12** [comment]
We have addressed all the above points in the updated version
